### PR TITLE
Opttimisation + modernise code

### PR DESCRIPTION
**Pull request by DebHugo**
I replace `InventoryTickTask` class to `onUpdate` function in `InventoryEntity` class

### CODE REVIEW

**Comment by tedo0627** [comment]
Entity is a dummy, and I think there is something odd about update Inventory from that dummy. I don't think Entity and Inventory are tied together.
Also, InventoryUI is done by spawning the Entity, but if it is done in a packet, it is not possible to call onUpdate of the Entity.
(DeepL)

**Comment by DebHugo** [comment]
I don't really understand why the entity and the inventory are not linked.
The entity is already using the number of slots in the inventory, and this change, without a task, can reduce bugs.
However, where entity is called as a packet? I don't see that in the code.
Sorry for my late reply

**Comment by tedo0627** [comment]
If the user clicks on an Entity and opens the Inventory held by that Entity, I think such an implementation would be fine. However, since that is not the case and Entity is a dummy, I would not link.
Also, since the Entity exists in the CustomInventory class, I think there is something different about calling the inventory tick from the Entity in the InventoryUI design.

Why would eliminating tasks reduce bugs?

There is no code in this repository that uses packets. However, this fork does use packets, and such an implementation may be done in the future.
https://github.com/sky-min/CustomInventory

**Comment by DebHugo** [comment]
I understand why an implementation can be confusing. The problem with the task is to take all players and not just players in the inventory and this implementation helped to fix that

**Comment by tedo0627** [comment]
If taking all players would significantly slow down the processing speed, there would be a problem, but that's not really the case, so it's not a particular problem.

**Comment by DebHugo** [comment]
ok

**Pull request closed without merging**
